//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premiumstress.Data.Blog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Premiumstress.Core.Domain.Blog;
    using Premiumstress.Core.Domain;

    public partial class PremiumStressEntities : DbContext
    {

        public PremiumStressEntities()
            : base("name=PremiumStressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogCategory> BlogCategories { get; set; }
        public virtual DbSet<BlogComment> BlogComments { get; set; }
        public virtual DbSet<BlogCommentReply> BlogCommentReplies { get; set; }
        public virtual DbSet<BlogVideo> BlogVideos { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Imagelink> Imagelinks { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostComment> PostComments { get; set; }
        public virtual DbSet<ShortFilm> ShortFilms { get; set; }
        public virtual DbSet<ShortFilmCategory> ShortFilmCategories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
